// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeRfStsMadn_T-uC5PGQyt7GIebdG-0E',
    appId: '1:362923892269:web:8fd0e72a6030a0e4a2e2a4',
    messagingSenderId: '362923892269',
    projectId: 'smartkitchen-dd50c',
    authDomain: 'smartkitchen-dd50c.firebaseapp.com',
    storageBucket: 'smartkitchen-dd50c.firebasestorage.app',
    measurementId: 'G-8G4KYVTEHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6z4Bd_HWkzkYQ762gilhdXviVXSLfJ8',
    appId: '1:362923892269:android:7ca45a384ed1a7fea2e2a4',
    messagingSenderId: '362923892269',
    projectId: 'smartkitchen-dd50c',
    storageBucket: 'smartkitchen-dd50c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYr1FDoaPOsuF1CgjliA6KccNLu3OlrGg',
    appId: '1:362923892269:ios:1e721295b4523d6ca2e2a4',
    messagingSenderId: '362923892269',
    projectId: 'smartkitchen-dd50c',
    storageBucket: 'smartkitchen-dd50c.firebasestorage.app',
    iosBundleId: 'com.example.kitchensync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYr1FDoaPOsuF1CgjliA6KccNLu3OlrGg',
    appId: '1:362923892269:ios:1e721295b4523d6ca2e2a4',
    messagingSenderId: '362923892269',
    projectId: 'smartkitchen-dd50c',
    storageBucket: 'smartkitchen-dd50c.firebasestorage.app',
    iosBundleId: 'com.example.kitchensync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeRfStsMadn_T-uC5PGQyt7GIebdG-0E',
    appId: '1:362923892269:web:764c271bd3907cd3a2e2a4',
    messagingSenderId: '362923892269',
    projectId: 'smartkitchen-dd50c',
    authDomain: 'smartkitchen-dd50c.firebaseapp.com',
    storageBucket: 'smartkitchen-dd50c.firebasestorage.app',
    measurementId: 'G-5C8GX6W7JJ',
  );
}
